CMPUT301F20T21/Book_Friends

app/src/main/AndroidManifest.xml
as per https://developer.android.com/training/basics/network-ops/connecting and [this SO answer](https://stackoverflow.com/a/57761916/7358099)
=> chore: add internet permissions to manifest

app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/LoginActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/LoginViewModel.java, app/src/main/res/layout/activity_login.xml
- Move login controller code to view model.
=> refactor: move login controller to view model

app/src/main/AndroidManifest.xml, app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/CreateAccountActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/LoginActivity.java, app/src/main/res/layout/activity_create.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/strings.xml
Creating ui for creating account, go to this page by clicking "create account" in log in page.
Errors will be shown if the input of any field is missing.
Error will be shown if the confirmed password and new password do not match.
=> Create account activity

app/src/main/java/com/cmput301f20t21/bookfriends/entities/Book.java, app/src/main/java/com/cmput301f20t21/bookfriends/services/BookService.java
not yet fleshed out. can we discuss and keep working on this?
=> feat: add Book entity and BookService

app/src/main/java/com/cmput301f20t21/bookfriends/entities/User.java, app/src/main/java/com/cmput301f20t21/bookfriends/services/AuthService.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/LoginViewModel.java
allow us to get username after log in by doing: `AuthService.getInstance().getCurrentUser().getUsername();`
=> feat: store username in auth service

app/src/main/res/layout/activity_create.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/colors.xml
make text field transparent, renaming some id names, and fix hardcoded colors
Before:
After:
=> style: minor fixes

app/src/main/java/com/cmput301f20t21/bookfriends/ui/add/AddEditActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/BorrowedListFragment.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/LibraryFragment.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/OwnedListFragment.java, app/src/main/res/layout/borrowed_list_book.xml, app/src/main/res/layout/fragment_library.xml, app/src/main/res/layout/owned_list_book.xml
Move the add button to OwnerFragment
<details><summary>A small demo</summary>
<p>
</p>
</details>
=> refactor: move add book button to OwnerFragment

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/cmput301f20t21/bookfriends/ui/add/AddEditActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/scanner/ScannerActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/scanner/ScannerAddActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/scanner/ScannerBaseActivity.java, app/src/main/res/layout/activity_scanner.xml, app/src/main/res/menu/scanner_add_menu.xml, app/src/main/res/values/strings.xml
- create a scanner activity with its own layout that provides any extending children activity the functionality to scan barcodes. Any class that extends this class should take care of what to do with the scanned barcode.
- create a bare bone Scanner Add activity that works specifically for adding a book from scanned isbn code.
- actual adding book functionality from received isbn barcode, e.g. the data communication between add-edit and the scanner-add
- any extra data fetching upon successful scan (e.g. book info grabbed from internet)
=> feat: create base/basic scanner activity

.github/tests.yml, .github/workflows/gradle.yml, app/src/main/res/layout/activity_login.xml
`build`: build the app apk and the intent tests, upload to firebase test lab
`unitTest`: run app unit tests
=> chore: setup actions to build and run tests

app/src/main/java/com/cmput301f20t21/bookfriends/ui/add/AddEditActivity.java
master broken right now, it was me deleting the import. :cry:
=> fix: add missing glide import

app/src/main/java/com/cmput301f20t21/bookfriends/enums/LOGIN_ERROR.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/component/BaseBookListAdapter.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/LoginActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/LoginViewModel.java, app/src/main/res/values/strings.xml
* Refactor empty checking to ViewModel
* Add javadoc to all methods
* Update error message for login
=> refactor & doc on LoginActivity

.github/workflows/gradle.yml
need to merge to see if it works.
=> chore: make CI use test google-services.json

app/src/main/res/menu/bottom_nav_menu.xml
=> chore: change "Browse" navigation icon from notification to search

app/build.gradle, app/src/main/java/com/cmput301f20t21/bookfriends/BookFriendsAppGlideModule.java, app/src/main/java/com/cmput301f20t21/bookfriends/entities/Book.java, app/src/main/java/com/cmput301f20t21/bookfriends/repositories/BookRepository.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/add/AddEditActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/add/AddEditViewModel.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/component/BaseBookListAdapter.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/BorrowedViewModel.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/OwnedViewModel.java, app/src/main/res/layout/item_book_list.xml
- use firebase glide module to fetch book image
- image name still kept to book.getId() + "cover"
- remove unnecessary checks for image creation/deletion
=> refactor: remove Book.imageName and ready to use toObject.

app/src/main/java/com/cmput301f20t21/bookfriends/ui/add/AddEditActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/scanner/ScannerAddActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/scanner/ScannerBaseActivity.java, app/src/main/res/layout/add_edit_activity.xml
integrated with add/edit book activity
=> feat: scan isbn and confirm to autofill to book

app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/OwnedListFragment.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/OwnedViewModel.java, app/src/main/res/layout/owned_filter_menu.xml
make the filter functionality work
might want to discuss if we want to keep the filter after switching to an new activity or fragment
if so we have to use SharedPreferences to store the states
=> feat: add filter functionality

app/src/main/java/com/cmput301f20t21/bookfriends/repositories/BookRepository.java, app/src/main/java/com/cmput301f20t21/bookfriends/repositories/RequestRepository.java, app/src/main/java/com/cmput301f20t21/bookfriends/repositories/api/IBookRepository.java, app/src/main/java/com/cmput301f20t21/bookfriends/repositories/api/IRequestRepository.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/borrow/RequestedListAdapter.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/borrow/RequestedListFragment.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/borrow/RequestedViewModel.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/browse/BrowseViewModel.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/BorrowedViewModel.java, app/src/test/java/com/cmput301f20t21/bookfriends/fakes/repositories/FakeBookRepository.java
showing a list of requested books requested by current user
=> feat: requested book list integration

app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/OwnedDetailActivity.java
<details><summary> Available Books: </summary>
<p>
</p>
</details>
<details><summary> Other Books: </summary>
<p>
</p>
</details>
=> feat: only enable book editing for available books

app/src/main/AndroidManifest.xml, app/src/main/java/com/cmput301f20t21/bookfriends/enums/REQUEST_STATUS.java, app/src/main/java/com/cmput301f20t21/bookfriends/enums/SCAN_ERROR.java, app/src/main/java/com/cmput301f20t21/bookfriends/repositories/api/RequestRepository.java, app/src/main/java/com/cmput301f20t21/bookfriends/repositories/impl/RequestRepositoryImpl.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/owned/AcceptedOwnedDetailActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/owned/AcceptedOwnedDetailViewModel.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/owned/OwnedListFragment.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/owned/RequestViewModel.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/scanner/ScannerAddActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/scanner/ScannerBaseActivity.java, app/src/main/res/values/strings.xml
- implemented scan to hand over accepted book
=> feat: implemented scan to hand over

app/src/main/java/com/cmput301f20t21/bookfriends/repositories/api/RequestRepository.java, app/src/main/java/com/cmput301f20t21/bookfriends/repositories/impl/RequestRepositoryImpl.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/borrowed/BorrowedListFragment.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/borrowed/BorrowedViewModel.java
Fully integrated borrowed tab
Small Demo: https://youtu.be/6WT4u0-4S_M
=> feat: fully integrate borrowed tab

app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/CreateAccountActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/CreateAccountViewModel.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/LoginActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/login/LoginViewModel.java
* get rid of Android Studio Warnings
* added some javadoc comments
To every Java file in login Package
=> refactor & doc: fix warnings and add javadoc

app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/owned/MapDialog.java
Auto suggestions require money, so an alternative solution is to allow users to specify geo location by clicking on the map.
=> Feat: Users can click on map

app/src/main/java/com/cmput301f20t21/bookfriends/entities/Book.java, app/src/main/java/com/cmput301f20t21/bookfriends/repositories/api/BookRepository.java, app/src/main/java/com/cmput301f20t21/bookfriends/repositories/impl/BookRepositoryImpl.java, app/src/main/java/com/cmput301f20t21/bookfriends/services/BookFriendsFirebaseMessagingService.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/add/AddEditViewModel.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/owned/OwnedViewModel.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/owned/RequestViewModel.java, app/src/test/java/com/cmput301f20t21/bookfriends/fakes/repositories/FakeBookRepository.java, app/src/test/java/com/cmput301f20t21/bookfriends/viewmodels/AddEditBookViewModelUnitTest.java
- assign unique id for image using android UUID and current username. By doing this, we can upload image first then get the image url and pass it to add/edit book method, keeping the add/edit method clean.
- map Document/QuerySnapshot to Book in bookRepository.
=> refactor: unique image name, add book, and edit book

app/src/main/res/layout/fragment_profile.xml, app/src/main/res/layout/item_book_list.xml
=> feat: truncate book title with three dots

app/src/main/java/com/cmput301f20t21/bookfriends/ui/borrow/accepted/AcceptedDetailActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/component/BaseDetailActivity.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/component/MeetLocationDialog.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/library/owned/AcceptedOwnedDetailActivity.java
<details><summary>seeing as the owner, after clicking on the accepted book in owned list: </summary>
</details>
<details><summary>same behavior clicking on the button</summary>
</details>
=> feat: owner can see map location in accepted detail

app/src/main/java/com/cmput301f20t21/bookfriends/services/BookFriendsFirebaseMessagingService.java, app/src/main/java/com/cmput301f20t21/bookfriends/ui/profile/ProfileSearchFragment.java
also fix user profile search glitch.
=> fix: notification onclick went to wrong activity.
